export const dummyTable = [
  {
    notification_id: "1",
    notification_type: "You have a new message!",
    date: "01/01/2020",
    details: "Lorem Ipsum is simply dummy text of industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    seen: false,
  },
  {
    notification_id: "1",
    notification_type: "Workshop on Machine Learning",
    date: "01/01/2020",
    details: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    seen: false,
  },
  {
    notification_id: "1",
    notification_type: "Hey there, young padawan!",
    date: "01/01/2020",
    details: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    seen: false,
  },
  {
    notification_id: "1",
    notification_type: "Hello there, general Kenobi!",
    date: "01/01/2020",
    details: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    seen: false,
  },
  {
    notification_id: "1",
    notification_type: "Discount on Bohubrihi!",
    date: "01/01/2020",
    details: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    seen: false,
  },
  {
    notification_id: "1",
    notification_type: "Hey, there",
    date: "01/01/2020",
    details: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    seen: false,
  },
  {
    notification_id: "1",
    notification_type: "Hey, there",
    date: "01/01/2020",
    details: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    seen: false,
  },
  {
    notification_id: "1",
    notification_type: "Hey, there",
    date: "01/01/2020",
    details: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    seen: false,
  },
  {
    notification_id: "1",
    notification_type: "Hey, there",
    date: "01/01/2020",
    details: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    seen: false,
  },
  {
    notification_id: "1",
    notification_type: "Hey, there",
    date: "01/01/2020",
    details: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    seen: false,
  },
  {
    notification_id: "1",
    notification_type: "Hey, there",
    date: "01/01/2020",
    details: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    seen: false,
  },
  {
    notification_id: "1",
    notification_type: "Hey, there",
    date: "01/01/2020",
    details: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    seen: false,
  },                    
];